replicaCount: 1
image:
  tag: "dev-9-a8da9d63"
  repository: docker.io/elioxrom/mc-user-fastapi
resources:
  requests:
    cpu: 150m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 384Mi
autoscaling:
  enabled: false
networkPolicy:
  enabled: false
